const tipos = {
    bug : './sourses/tipos/bug.png',
    dark : './sourses/tipos/dark.png',
    dragon : './sourses/tipos/dragon.png',
    electric : './sourses/tipos/electric.png',
    fairy : './sourses/tipos/fairy.png',
    fighting : './sourses/tipos/fighting.png',
    fire : './sourses/tipos/fire.png',
    flying : './sourses/tipos/flying.png',
    ghost : './sourses/tipos/ghost.png',
    grass : './sourses/tipos/grass.png',
    ground : './sourses/tipos/ground.png',
    ice : './sourses/tipos/ice.png',
    normal : './sourses/tipos/normal.png',
    poison : './sourses/tipos/poison.png',
    psychic : './sourses/tipos/psychic.png',
    rock : './sourses/tipos/rock.png',
    steel : './sourses/tipos/steel.png',
    water : './sourses/tipos/water.png',
}
